language: node_js
node_js:
- '4.1'
before_install:
- npm --version
before_script:
- npm install
notifications:
  email: true
after_failure: cat /home/travis/build/mgechev/angular2-seed/npm-debug.log
script: npm test